language: perl

sudo: false

perl:
    - "5.26"

install:
    - "export PATH=$PWD/bin:$PATH"

script:
    - "legsta --version"
    - "legsta --help"
    - "! legsta --doesnotexist"
    - "legsta test/NC_006368.fna"
    - "legsta test/NC_018140.fna"
    - "legsta test/NC_006368.fna | grep '4'"
    - "legsta test/NC_018140.fna | grep '734'"
