language: perl

sudo: false

perl:
    - "5.26"

install:
    - "export PATH=$PWD/bin:$PATH"

script:
    - "isPcr | grep Situ"
    - "grep --version"
    - "legsta --version"
    - "legsta --help"
    - "! legsta --doesnotexist"
    - "legsta test/NC_006368.fna"
    - "legsta test/NC_018140.fna"
    - legsta test/NC_006368.fna | grep -P "1\t1\t4\t3\t1\t1\t1"
    - legsta test/NC_018140.fna | grep -P "734\t2\t6\t17\t1\t1\t8"

