language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - multiarch-support
            - "libc6:i386"

install:
    - "export PATH=$PWD/bin:$PATH"
    - "curl https://raw.githubusercontent.com/tseemann/any2fasta/master/any2fasta > bin/any2fasta"
    - "chmod +x bin/any2fasta"

script:
    - "isPcr 2>&1 | grep Situ"
    - "legsta --version"
    - "legsta --help"
    - "! legsta --doesnotexist"
    - legsta test/NC_006368.fna
    - legsta --quiet --noheader test/NC_006368.fna | wc -l | grep '^1$'
    - legsta test/NC_006368.fna | grep -P "1\t1\t4\t3\t1\t1\t1"
    - legsta test/NC_018140.fna | grep -P "734\t2\t6\t17\t1\t1\t8"
    - legsta --csv test/NC_018140.fna | grep -P "2,6,17"
    - legsta test/missing_flaA.fna | grep -P "\t-\t"
    - "! (legsta --quiet test/NC_006368.fna |& grep Loaded)"
    - "legsta /dev/null 2>&1 | grep ERROR"
    - legsta test/CR628336.1.gbk.gz | grep -P "1\t1\t4\t3\t1\t1\t1\t1"
